permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

#  author info 
author: 
  name: Samuelnotes
  email: samuelwang95@gmail.com
  link: http://www.samuelnotes.cn
  github: http://github.com/samuelhehe

# 
title: Samuelnotes
description: Samuelnotes 
url: http://www.samuelnotes.cn
rss_url: /pages/atom.xml

# avatar
avatar:	http://www.samuelnotes.cn/images/headicon.jpg
favicon: http://www.samuelnotes.cn/images/slogo.jpg

# google analytics 璁剧疆
#ga:
 # id: 71372190
 # url: samuelnotesweb

# disqus 璁剧疆
disqus:
shortname:samuelnotes

# twitter
twitter:samuelnotes
